### ISSUE TITLE
Error: not a valid identifier

### ISSUE THREAD

**Issue by QCoughlin** [SamuelSchlesinger/encrypted-message-cli#1]
> Quinns-MacBook-Pro:encrypted-message-cli qcoughlin$ read quinn sam ~/Downloads/very_long_message_to_quinn
> -bash: read: `/Users/qcoughlin/Downloads/very_long_message_to_quinn': not a valid identifier

Terminal pauses for a very long time, then spits out "not a valid identifier" error.

**Comment by SamuelSchlesinger** [comment]
You should be writing `./messaging quinn sam ~/Downloads/very_long_message_to_quinn`.

**Comment by QCoughlin** [comment]
Solved thnx
